### ISSUE TITLE
extend Leaflet layer control to add line of header text?

### ISSUE THREAD

**Issue by JackDougherty** [JackDougherty/bikemapcode#155]
@ilyankou  I would like to add a line of text at the top of the layer control panel, to serve as a proxy title for the map. I'm wondering if there is a way to extend Leaflet layer control to do this? http://leafletjs.com/reference-1.0.0.html#control-layers

![add-text](https://cloud.githubusercontent.com/assets/649719/18333204/0ad44052-753b-11e6-9a71-0f74e06d314e.png)

**Comment by cmwright93** [comment]
What was the coding solution to the 'extend Leaflet layer control to add line of header text' I am relatively new to leaflet and coding in general and have not been able to find the exact coding for this. Thanks :)

**Comment by cmwright93** [comment]
Thank you for your help! Is this for JQuery? I do not use the '$' in my coding so I am not sure how that would translate to strictly Leaflet/Javascript usage, sorry still learning.

**Comment by ilyankou** [comment]
@cmwright93 Pure JavaScript is long and would be something like that: https://www.w3schools.com/jsref/met_node_insertbefore.asp

But I'd recommend you use jQuery because it makes your development much more efficient.

**Comment by cmwright93** [comment]
I would like to learn jQuery and incorporate it into my work. Thank you again for your help :)
